name: Navigation Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  navigation-unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run navigation unit tests
      run: npm run test -- src/tests/e2e/navigation-click-paths.test.tsx
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: navigation-unit-test-results
        path: coverage/

  navigation-e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Start application
      run: npm run preview &
      env:
        PORT: 8080
    
    - name: Wait for application to start
      run: npx wait-on http://localhost:8080
    
    - name: Run Cypress E2E tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run preview
        wait-on: 'http://localhost:8080'
        spec: cypress/e2e/navigation-first-click.cy.ts
        browser: chrome
    
    - name: Upload Cypress screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    
    - name: Upload Cypress videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos

  navigation-check-summary:
    needs: [navigation-unit-tests, navigation-e2e-tests]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Navigation Test Summary
      run: |
        echo "## Navigation on First Click Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ needs.navigation-unit-tests.result }}" == "success" ]; then
          echo "✅ Unit Tests: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Unit Tests: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.navigation-e2e-tests.result }}" == "success" ]; then
          echo "✅ E2E Tests: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ E2E Tests: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Coverage:" >> $GITHUB_STEP_SUMMARY
        echo "- Home → Dashboard navigation" >> $GITHUB_STEP_SUMMARY
        echo "- Dashboard → Detail → Back flow" >> $GITHUB_STEP_SUMMARY
        echo "- Auth-gated route navigation" >> $GITHUB_STEP_SUMMARY
        echo "- Error/empty state navigation" >> $GITHUB_STEP_SUMMARY
        echo "- Single-click validation" >> $GITHUB_STEP_SUMMARY
        echo "- Performance threshold checks" >> $GITHUB_STEP_SUMMARY