
name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master, dev, development ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        # This uses the existing eslint command if available in the project
        run: npm run lint || echo "Linting not configured, skipping"

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Type check with strict settings
        run: npx tsc --project tsconfig.ci.json --noEmit

  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Check bundle size
        run: |
          echo "Bundle size analysis:"
          find dist -type f -name "*.js" -o -name "*.css" | xargs ls -lh
